[package]
name = "iso_country"
version = "0.2.0"
edition = "2021"
publish = false
homepage = "https://github.com/pzol/iso_country"
repository = "https://github.com/pzol/iso_country"

[dependencies]
serde = { version = "1.0.197", optional = true }

[dev-dependencies]
serde_json = "1.0.114"
